# Generated by Django 4.1.2 on 2022-10-19 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name_plural": "Autores"},
        ),
        migrations.AlterModelOptions(
            name="pais",
            options={"verbose_name_plural": "Paises"},
        ),
        migrations.AlterModelOptions(
            name="transporte",
            options={"verbose_name_plural": "Transportes"},
        ),
    ]
