# Generated by Django 4.1.2 on 2022-11-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0003_remove_pais_fechaindependencia_pais_fechasalida"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pais",
            name="fechaSalida",
        ),
        migrations.AddField(
            model_name="pais",
            name="satisfaccion",
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
