# Generated by Django 4.1.2 on 2022-11-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0004_remove_pais_fechasalida_pais_satisfaccion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pais",
            name="habitantes",
        ),
        migrations.AddField(
            model_name="pais",
            name="ciudad_visitada",
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
