# Generated by Django 4.1.2 on 2022-11-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0007_pais_itinerario"),
    ]

    operations = [
        migrations.AddField(
            model_name="pais",
            name="año",
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pais",
            name="foto",
            field=models.ImageField(null=True, upload_to="pais"),
        ),
    ]
