# Generated by Django 4.1.2 on 2022-11-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0010_alter_pais_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pais",
            name="foto",
            field=models.ImageField(null=True, upload_to="foto"),
        ),
    ]
